### ISSUE TITLE
Find / exercise GUI for locating bugs in the code

### ISSUE THREAD

**Issue by aashish24** [CDAT/cdat#1214]

**Comment by vvpalav** [comment]
It would help if anyone who has better understanding of UVCDAT provides suggestions to do this efficiently. I am mainly looking for things I should be testing. Thanks.

**Comment by hgohil2805** [comment]
1 - Merge icons missing. Click on the cell with the plot, then click on the cell below it. Shows a merge icon on top without any icon

2 - The above exception also pops up an exception. 

Will add the steps in detail into the document.

**Comment by mcenerney1** [comment]
It would be very useful to have the capability to test diagnostics by specifying all of the inputs on the command line without bringing up the gui.  This is what what happens with diags.py but it's not guaranteed to duplicate the gui output faithfully.

**Comment by painter1** [comment]
diags.py is guaranteed to produce *different* results from the GUI. 
    The script calls plot().  The GUI uses a drag-and-drop mechanism. 
    The templates are different, but beyond that, the interface to the
    graphics is so different that I don't think it is realistic to
    expect them to be the same.
    
    On 4/13/15 11:15 AM, James McEnerney
      wrote:
    
    
      
      It would be very useful to have the capability to test
        diagnostics by specifying all of the inputs on the command line
        without bringing up the gui. This is what what happens with
        diags.py but it's not guaranteed to duplicate the gui output
        faithfully.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by vvpalav** [comment]
documentation creation is tracked by using #1215

**Comment by vvpalav** [comment]
@aashish24 .. can you please send me an email with any information you have about automated test cases.

**Comment by vvpalav** [comment]
#1220 .. found issue in colormap .. just added here for tracking

**Comment by aashish24** [comment]
http://www.paraview.org/gitweb?p=QtTesting.git

**Comment by remram44** [comment]
Does this work? More importantly, is it possible at all to wrap this for Python?

**Comment by vvpalav** [comment]
I found following bugs while doing testing of UVCDAT. I was using latest VisTrails but rest of the stuff was old before 2.2: https://drive.google.com/file/d/0B2ACuiq8tB3RMnZDbS1QaDREUFE/view?usp=sharing

Please let me know which ones are valid. I can create issues for tracking

**Comment by vvpalav** [comment]
Created #1277 for exception while loading variable and changing dimensions.

**Comment by vvpalav** [comment]
created #1278 to cosmetic enhancement issue while adding new cells as row or column

**Comment by vvpalav** [comment]
created #1279 to address minor issue with console of calculator widget

**Comment by vvpalav** [comment]
created #1276 by @remram44 to address exception while exporting cells as a images

**Comment by vvpalav** [comment]
created #1274 by @remram44 to handle unresolved references in code

**Comment by vvpalav** [comment]
created #1275 to handle minor error in GUI related to toolbar

**Comment by vvpalav** [comment]
created #1280 for Divide By Zero exception in Scatter Plot

**Comment by vvpalav** [comment]
created #1281 for cosmetic bug in Scatter plot

**Comment by vvpalav** [comment]
created #1282 for boxfill plot with clt

**Comment by aashish24** [comment]
@remram44 it should be possible to wrap this in python but may require looking into Shiboken or other means.

**Comment by vvpalav** [comment]
@aashish24 @doutriaux1 @remram44 .. I have created issues I found while doing testing of UVCDAT GUI. Please review those and confirm if they are valid otherwise we can close if anything is invalid.

**Comment by aashish24** [comment]
thanks @vvpalav I will do it after meeting unless someone else beats me to it.

**Comment by vvpalav** [comment]
created #1283 related to 3D plots graphic method editor

**Comment by vvpalav** [comment]
created #1284 Error while plotting mesh fill plot. @remram44 can you please verify this one on your machine.

**Comment by hgohil2805** [comment]
All,
In order to make the GUI testing process simpler and more automated we are trying a tool called Sikuli (http://www.sikuli.org/) which basically helps record and replay all the actions we can perform. It is quite simple to use and manage and can take care of the manual testing that everyone has to perform before the release. We are still trying to figure out how and where to set the tool up and @remram44 has some ideas  which we will be trying soon. Here's the link for how the test runs,   

https://www.dropbox.com/s/muhvdxki8z1mz9m/testfile.mkv?dl=0

everything that happens(Click, double click, drag and drop)  after I click the run button is automated and the test stops at the end after it compares the correct plot with the plot created. Have a look and let us know what you guys think.

**Comment by hgohil2805** [comment]
https://github.com/UV-CDAT/uvcdat/issues/585

**Comment by remram44** [comment]
@hgohil2805 This looks really slow. Is it because of pixel density?

The idea would be to use a well-defined environment (Linux with set resolution/WM) to run this, and to go through it on Travis/buildbot. Changes that affect the GUI would need to come with a change in the script (same way we update baselines now) so I take it that devs would need to be able to set up the same testing env on their machine? (vagrant might help there but this shouldn't mean rebuildling)

**Comment by hgohil2805** [comment]
@remram44 That's because before clicking on anything I am directing it to wait for 10 seconds (this can be changed)  to make sure that the screen loads. It can be made faster on a faster machine as mine is quite slow.
