### ISSUE TITLE
Thermo test suite needs to be moved to test suite

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/cdat#1783]
voila

**Comment by sankhesh** [comment]
Branch [thermo_testing](https://github.com/UV-CDAT/uvcdat/tree/thermo_testing) adds some `Thermo` tests but they are crashing right now.

@doutriaux1 Need your help understanding why they crash

**Comment by doutriaux1** [comment]
@sankhesh I will run that branch and get back to you

**Comment by sankhesh** [comment]
Thanks @doutriaux1. Just run 

```
ctest -V -R thermo

```

to run the new tests.

**Comment by aashish24** [comment]
@sankhesh @doutriaux1 please have a look.

**Comment by aashish24** [comment]
Are we still working on this issue?

**Comment by sankhesh** [comment]
@aashish24,

I added about 5-6 tests for the `Thermo` package in the branch [thermo_testing] (https://github.com/UV-CDAT/uvcdat/tree/thermo_testing) but they were failing because the package had issues. @doutriaux1 fixed some issues and the last I heard, only one test fails now. @doutriaux1 Could you please confirm this?

IMHO, we can just disable that test and merge this branch for now.
